import './globals.css'
import { space_grotesk } from './font/font'
//components
import Header from '@/components/header/Header.component'
import SnackBar from '@/components/snack-bar/SnackBar.component'
import Overlay from '@/components/overlay/Overlay.component'
//provider
import AppProvider from '@/components/app-provider/AppProvider.component' 


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,params
}: {
  children: React.ReactNode
  params: string
}) {


  return (
    <html lang="en">
      <body className={space_grotesk.className} style={{backgroundColor: '#f9fafa'}}>
        {/* Header */}
        <AppProvider>
        <Header/>
        <div className="" style={{margin:'0px auto', maxWidth: '1440px'}}>
          <SnackBar/>
        {children}
        </div>
      <div className="fixed w-full h-[10px] top-0 left-0" style={{zIndex: '90'}}>
        <Overlay/> 
      </div>
        </AppProvider>
        </body>
    </html>
  )
}
