import './globals.css'
import {Space_Grotesk  } from 'next/font/google'
//components
import AnnouncementBar from '@/components/announcement-bar/AnnouncementBar.component'
import Header from '@/components/header/Header.component'
import SnackBar from '@/components/snack-bar/SnackBar.component'
//redux
import Providers from './redux/Provider'

const inter = Space_Grotesk({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,params
}: {
  children: React.ReactNode
  params: string
}) {


  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Header */}
        <Providers>
        <Header/>
        <div className="" style={{margin:'0px auto', maxWidth: '1440px'}}>
          <SnackBar/>
        {children}
        </div>
        </Providers>
        </body>
    </html>
  )
}
